### PR TITLE
Fix/plotdata

### PR DESCRIPTION
**Pull request by meganrm**
Time Estimate or Size
=======
 xsmall

Problem
=======
`getPlotData` is typed to return `Plot[]` but when I logged what I got, it returns an object with `{version: 1, data: Plot[]}`, so I changed the functions to actually return Plot[]

Solution
========
Adjust the return of getPlotData to unpack the data

## Type of change
Please delete options that are not relevant.

* Bug fix (non-breaking change which fixes an issue)
* Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Review by toloudis — COMMENTED** [review]
What about all the plots in our example trajectories that are displayed in the simularium-website? Do they go through a different code path than this?

**Comment by meganrm** [comment]
> What about all the plots in our example trajectories that are displayed in the simularium-website? Do they go through a different code path than this? (would this change break them or are they already broken and this is fixing it?)

this is a breaking change, but the fix is really small: remove a `.data` when unpacking the data. I could have changed the typing but my thinking here is that the version is really for the internals of the viewer, and anyone consuming the plot data shouldn't be managing/caring about the version number

**Comment by toloudis** [comment]
> this is a breaking change, but the fix is really small: remove a `.data` when unpacking the data. I could have changed the typing but my thinking here is that the version is really for the internals of the viewer, and anyone consuming the plot data shouldn't be managing/caring about the version number

So the fix goes in simularium-website, or where? Is there already another PR that fixes the breakage?

**Comment by meganrm** [comment]
> > this is a breaking change, but the fix is really small: remove a `.data` when unpacking the data. I could have changed the typing but my thinking here is that the version is really for the internals of the viewer, and anyone consuming the plot data shouldn't be managing/caring about the version number
> 
> So the fix goes in simularium-website, or where? Is there already another PR that fixes the breakage?

it's here https://github.com/simularium/simularium-website/pull/522

**Comment by ShrimpCryptid** [comment]
(Left an approval since I saw that this was urgent, but will defer to Dan since there was an existing discussion)

**Pull request merged**
